### PR TITLE
Improvements to CLI to add support for STDIN/OUT 

### PR DESCRIPTION
**Pull request by stevegeek**
Makes read/writes async and also adds some error checking.

Now for CLI if:
'-i' is specified without a parameter it defaults to stdin, if it is omitted no input is assumed.
'-o' is specified without parameter or omitted then defaults to stdout
'-g' is specified without a parameter or omitted defaults to stdin, (and if both input and grammar are from stdin then they are accepted in sequence, first grammar is input then 'input' )

I have tested it generally but this should be further tested by someone who can def verify output is correct.

Feedback/more testing/changes/hate/love welcome

### CODE REVIEW

**Comment by tolmasky** [comment]
So basically the idea was the following:
1. If no -g or -o, then take the grammar from stdin and print the compiled grammar to stdout (something like gammar_generator | cli.js > result)
2. If -g but no -o, take grammar from -g and print to stdout ( something like cli.js -g grammar.language > result)
3. If -g and -i === -, take grammar from -g and use stdin for input to be parsed (something like cat objective_j_file | cli.js -g objj_gammar.language > result)

Does this do that? If so, I will take it in.

**Comment by tolmasky** [comment]
Also (just looking at your second commit). The idea is that grammar and input can't BOTH be stdin

**Comment by tolmasky** [comment]
Oops, didn't mean to close this

**Comment by stevegeek** [comment]
1) yes
2) yes
3) no , will update it later

**Comment by stevegeek** [comment]
Oh btw, '-i -' is not parsed by nomnom if im not mistaken, it assumes the extra '-' on the command line is the start of a new command i think, so in this case the value of the input option is as below:
`cmd -i - -t`   then input === true
`cmd -t -i -`   then input === true
`cmd -i -t`     then input === true
`cmd -i file`   then input === 'file'
`cmd -t -i`    then input === ''  <- the odd one out

Will think about it more later when I have time

**Comment by stevegeek** [comment]
Ok now the examples in 1) 2) and 3) should all work as expected

eg
`echo 'start="a"' | node lib/language/cli.js -t -g languages/JavaScript.language -o out.txt` -> out to file, input from stdin
`node lib/language/cli.js -t -g languages/JavaScript.language`    -> out to stdout
`echo 'start="a"' | node lib/language/cli.js -t`  -> grammar from stdin , out to stdout
`echo 'start="a"' | node lib/language/cli.js -t -g languages/JavaScript.language -i`  -> input from stdin

**Comment by stevegeek** [comment]
Ah one sec, seen something I think

**Comment by stevegeek** [comment]
Ok think that works, sorry about all the commits!

**Comment by stevegeek** [comment]
@tolmasky have you had a chance to look further at this? I think it fulfills the requirement. I have been using it for a few days and seems fine

**Comment by tolmasky** [comment]
Yeah sorry I haven't gotten to this yet, just been super busy. I will try to get it merged in tonight.

**Comment by stevegeek** [comment]
No probs, no rush

**Comment by tolmasky** [comment]
I really dislike asynchronous IO for command line apps.

**Comment by stevegeek** [comment]
Ah ok, sorry about that

**Comment by tolmasky** [comment]
nothing to apologize for, your thing works exactly as described.

**Pull request merged**
